### ISSUE TITLE
App staging fails in the buildpack compile phase: "Unable to initialize apt package"

### ISSUE THREAD

**Issue by fureigh** [18F/cf-ex-drupal8#2]
Running `cf push` yields these updates:
```
   -----> Multi Buildpack version 1.0.3
   -----> Running buildpacks:
          https://github.com/cloudfoundry/apt-buildpack#v0.1.1
          https://github.com/cloudfoundry/php-buildpack#v4.3.70
   -----> Running go build supply
```
And then these errors:
```
   -----> Apt Buildpack version 0.1.1
          **ERROR** Unable to initialize apt package: open /etc/apt/trusted.gpg: no such file or directory
          **ERROR** Unable to run all buildpacks: Failed to run all supply scripts: exit status 13
   Failed to compile droplet: Failed to compile droplet: exit status 13
   Exit status 223
```

The problem existed before I updated the multi-buildpack to use cloud.gov's latest version of PHP (068845313fb7247d03e329181cb29bea36da1bd9).

Potentially relevant: https://github.com/cloudfoundry/cli/issues/1327

**Comment by fureigh** [comment]
@tadhg-ohiggins, this is the issue I mentioned. It's reproducible with the codebase that's currently in the `add-dockerized-example` branch.

**Comment by mogul** [comment]
No longer happening after other refactors/improvements.
