### ISSUE TITLE
Exited with code 127

### ISSUE THREAD

**Issue by cwilkescw** [18F/cf-ex-drupal8#23]
## User story
As a newbie and user of the repository following the READ.me file , I want to run the "docker-compose up" command so that I don't get the error:

database_1  | 2019-06-11T21:21:17.744629Z 0 [Note] mysqld: ready for connections.
database_1  | Version: '5.7.26'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
cf-ex-drupal8-master_web_1 exited with code 127

Using Docker Desktop for Windows Version 2.0.0.3 
Engine 18.06.02
Compose 1.23.2

## Definition of done
"exited with code 127" does not happen

**Comment by LindsayYoung** [comment]
Thanks for writing in! 

I was also having some set up issues that I was working on here #21, though I am getting a different error code. I will see if I can take a closer look in the next few days and keep you posted.

**Comment by cwilkescw** [comment]
Thank you! 

I just noticed that the docker-compose.yml file is calling for mysql 5.7
      image: mysql:5.7

As a sandbox user I only have access to mysql 5.6.27 as stated here:
     [https://cloud.gov/docs/services/relational-database/](url)

Could that be the issue?

**Comment by LindsayYoung** [comment]
Hi @cwilkescw! @mogul put in a fix and I just approved and merged it. if you pull down the latest on the master branch this should work for you.

**Comment by mogul** [comment]
My fix was for when `jq` exits with a code 5 at the end of `docker-compose up`... It may not help with this problem!

**Comment by cwilkescw** [comment]
This issue is no longer occurring in sandbox or prototyping.
